services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - storage:/app/.output/storage
    environment:
      NODE_ENV: production
    command: npm run start

volumes:
  storage: